# Generated by Django 2.0.7 on 2018-07-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180704_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='email',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
