# Generated by Django 2.0.7 on 2018-07-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180705_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
